# Generated by Django 6.0.5 on 2026-06-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Введите название игры')),
                ('photo', models.ImageField(upload_to='games/', verbose_name='Добавьте фото игры')),
                ('description', models.TextField(blank=True, verbose_name='Укажите описание игры')),
                ('url', models.URLField(verbose_name='Укажите ссылку для скачивания')),
            ],
        ),
    ]
