# Generated by Django 6.0.5 on 2026-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fighter_fatality'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='description',
            field=models.TextField(null=True, verbose_name='Укажите описание бойца'),
        ),
    ]
