# Generated by Django 6.0.5 on 2026-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_factsmk'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='views',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
